name: "GLADOS airport Checkin"

on:
  schedule:
    - cron: "0 23 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  checkin:
    runs-on: ubuntu-latest
    outputs:
      checkin_result: ${{ steps.run_checkin.outputs.checkin_result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-30 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run GlaDOS checkin
        id: run_checkin
        env:
          GR_COOKIE: ${{ secrets.GR_COOKIE }}
          cookie1: ${{ secrets.cookie1 }}
        run: |
          python3 ./checkin.py

      - name: Display checkin results
        run: |
          echo "签到结果："
          echo "${{ steps.run_checkin.outputs.checkin_result }}"

  notify:
    needs: checkin
    runs-on: ubuntu-latest
    if: always() && needs.checkin.result != 'cancelled'

    steps:
      - name: Trigger notification service
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ secrets.NOTIFICATION_REPO }}
          event-type: send-notification
          client-payload: |
            {
              "title": "GlaDOS签到通知",
              "content": "${{ needs.checkin.outputs.checkin_result || '签到失败，请检查账户信息以及网络环境' }}",
              "source": "glados",
              "timestamp": "${{ github.event.head_commit.timestamp || github.run_id }}"
            }
