name: "GLADOS airport Checkin"

on:
  schedule:
    - cron: "0 23 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-30 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sign
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_SSL: ${{ secrets.SMTP_SSL }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_NAME: ${{ secrets.SMTP_NAME }}
          cookie1: ${{ secrets.cookie1 }}
        run: |
          python3 ./checkin.py
